### ISSUE TITLE
ListLiteral não tá conseguindo pegar.

### ISSUE THREAD

**Issue by Gaobaofogo** [melosomelo/compiladores#1]
A expressão [1,2,3,4] tá indo como cada token separado em vez de ser ListLiteral. Tem que corrigir a regex.

**Comment by melosomelo** [comment]
Consegui melhorar isso daqui. Até agora tá aceitando literais de inteiros, reais, booleanos e strings. 

Uma coisa que temos que melhorar é que ele não aceita espaços entre os elementos. Caso queiramos melhorar isso, vamos ter que modificar a RegEx.
